runtime: python38

env: standard
instance_class: F1
entrypoint: gunicorn run:app --timeout 1000

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_instances: 1
  max_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1
  max_pending_latency: automatic
  max_concurrent_requests: 80