name: DB backup

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  database_url: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: DB Backup
      run: pg_dump ${{ env.database_url }} > database-dump.sql

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: ./database-dump.sql
        destination: spotify-wordcloud-dump/database-dump.sql
